"""
Configuration-related constants for Prompt Firewall MVP.
"""

class ConfigConstants:
    """Configuration-related constants."""
    
    # API Configuration
    API_HOST_ENV = "API_HOST"
    API_PORT_ENV = "API_PORT"
    API_WORKERS_ENV = "API_WORKERS"
    
    # Default Values
    DEFAULT_API_HOST = "0.0.0.0"
    DEFAULT_API_PORT = 8000
    DEFAULT_API_WORKERS = 4
    
    # Rate Limiting
    RATE_LIMIT_REQUESTS_PER_MINUTE_ENV = "RATE_LIMIT_REQUESTS_PER_MINUTE"
    RATE_LIMIT_WINDOW_MINUTES_ENV = "RATE_LIMIT_WINDOW_MINUTES"
    
    # Security
    CORS_ORIGINS_ENV = "CORS_ORIGINS"
    ALLOWED_HOSTS_ENV = "ALLOWED_HOSTS"
    
    # Database
    FIRESTORE_EMULATOR_HOST_ENV = "FIRESTORE_EMULATOR_HOST"
    FIRESTORE_EMULATOR_PROJECT_ID_ENV = "FIRESTORE_EMULATOR_PROJECT_ID"
    
    # Monitoring
    ENABLE_METRICS_ENV = "ENABLE_METRICS"
    METRICS_PORT_ENV = "METRICS_PORT"
    
    # Feature Flags
    ENABLE_OPENAI_DETECTION_ENV = "ENABLE_OPENAI_DETECTION"
    ENABLE_RATE_LIMITING_ENV = "ENABLE_RATE_LIMITING"
    ENABLE_AUDIT_LOGGING_ENV = "ENABLE_AUDIT_LOGGING"
    ENABLE_METRICS_COLLECTION_ENV = "ENABLE_METRICS_COLLECTION"
